apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-name
  labels:
    app: replicaset-app
    type: front-end
spec:
  template:
    metadata:
      name: pod-name-here
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
         - name: container-name-here
           image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end    