apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-name
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod-name
      labels:
          app: myapp
          type: front-end
          department: human-resource
          team: team-1
    spec:
      containers:
        - name: container-name
          image: nginx
  repilcas: 3